#
# In sdc, all clocks are related by default. This differs from ucf, where clocks are unrelated unless specified otherwise.

# SDR receiver timing constraints

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

#create_clock -period 5.000 -name diff_clock_clk_p -add [get_ports diff_clock_clk_p]
##create_clock -period 5.000 -name refclkin_n -add [get_ports refclkin_n]

#set_property IOSTANDARD LVDS [get_ports diff_clock_clk_p]
#set_property DIFF_TERM TRUE [get_ports diff_clock_clk_p]
#set_property PACKAGE_PIN L4 [get_ports diff_clock_clk_n]
#set_property IOSTANDARD LVDS [get_ports diff_clock_clk_n]
#set_property DIFF_TERM TRUE [get_ports diff_clock_clk_n]


#set_property IOSTANDARD LVCMOS25 [get_ports rst_n]
#set_property PACKAGE_PIN AE26 [get_ports rst_n]
create_clock -period 30.76899909973144500 -name channel_x_clk_p -add [get_ports channel_x_clk_p]
#create_clock -period 20.833 -name channel_y_clk_p -add [get_ports channel_y_clk_p]
#create_clock -period 20.833 -name channel_z_clk_p -add [get_ports channel_z_clk_p]


create_clock -period 5.00000000000000000 -name diff_clock_clk_p -add [get_ports diff_clock_clk_p]

# Ignore false path from clock input to clock input serdes
set_false_path -from [get_ports channel_x_clk_p] -to [get_pins -hier -filter {name =~ *rx*iserdes_c?/DDLY}]
set_false_path -from [get_clocks clk_out1_design_1_clk_wiz_0_0] -to [get_clocks clk_out2_design_1_clk_wiz_0_0]
set_false_path -from [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks clk_out1_design_1_clk_wiz_0_0] -to [get_clocks clk_out2_design_1_clk_wiz_0_0]
#set_false_path -from [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT1]]
# sof of vert cropping to dmd --- to see how much time it takes
#set_property IOSTANDARD LVCMOS33 [get_ports sof]
#set_property PACKAGE_PIN Y10 [get_ports sof]
#set_false_path -from [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT1]]

# debug -- count

#set_property IOSTANDARD LVCMOS18 [get_ports count_op]
#set_property PACKAGE_PIN E6 [get_ports count_op]

# Pin constraints
set_property IOSTANDARD LVDS_25 [get_ports channel_x_clk_p]
set_property DIFF_TERM TRUE [get_ports channel_x_clk_p]
set_property PACKAGE_PIN AD24 [get_ports channel_x_clk_n]
set_property IOSTANDARD LVDS_25 [get_ports channel_x_clk_n]
set_property DIFF_TERM TRUE [get_ports channel_x_clk_n]

set_property IOSTANDARD LVDS_25 [get_ports {channel_x_data_p[0]}]
set_property DIFF_TERM TRUE [get_ports {channel_x_data_p[0]}]
set_property PACKAGE_PIN AD26 [get_ports {channel_x_data_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_x_data_n[0]}]
set_property DIFF_TERM TRUE [get_ports {channel_x_data_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_x_data_p[1]}]
set_property DIFF_TERM TRUE [get_ports {channel_x_data_p[1]}]
set_property PACKAGE_PIN AB24 [get_ports {channel_x_data_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_x_data_n[1]}]
set_property DIFF_TERM TRUE [get_ports {channel_x_data_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_x_data_p[2]}]
set_property DIFF_TERM TRUE [get_ports {channel_x_data_p[2]}]
set_property PACKAGE_PIN AC26 [get_ports {channel_x_data_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_x_data_n[2]}]
set_property DIFF_TERM TRUE [get_ports {channel_x_data_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_x_data_p[3]}]
set_property DIFF_TERM TRUE [get_ports {channel_x_data_p[3]}]
set_property PACKAGE_PIN AB25 [get_ports {channel_x_data_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_x_data_n[3]}]
set_property DIFF_TERM TRUE [get_ports {channel_x_data_n[3]}]

set_property IOSTANDARD LVDS_25 [get_ports channel_y_clk_p]
set_property DIFF_TERM TRUE [get_ports channel_y_clk_p]
set_property PACKAGE_PIN AD21 [get_ports channel_y_clk_n]
set_property IOSTANDARD LVDS_25 [get_ports channel_y_clk_n]
set_property DIFF_TERM TRUE [get_ports channel_y_clk_n]

set_property IOSTANDARD LVDS_25 [get_ports {channel_y_data_p[0]}]
set_property DIFF_TERM TRUE [get_ports {channel_y_data_p[0]}]
set_property PACKAGE_PIN AC19 [get_ports {channel_y_data_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_y_data_n[0]}]
set_property DIFF_TERM TRUE [get_ports {channel_y_data_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_y_data_p[1]}]
set_property DIFF_TERM TRUE [get_ports {channel_y_data_p[1]}]
set_property PACKAGE_PIN AB19 [get_ports {channel_y_data_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_y_data_n[1]}]
set_property DIFF_TERM TRUE [get_ports {channel_y_data_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_y_data_p[2]}]
set_property DIFF_TERM TRUE [get_ports {channel_y_data_p[2]}]
set_property PACKAGE_PIN AA18 [get_ports {channel_y_data_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_y_data_n[2]}]
set_property DIFF_TERM TRUE [get_ports {channel_y_data_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_y_data_p[3]}]
set_property DIFF_TERM TRUE [get_ports {channel_y_data_p[3]}]
set_property PACKAGE_PIN AD19 [get_ports {channel_y_data_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_y_data_n[3]}]
set_property DIFF_TERM TRUE [get_ports {channel_y_data_n[3]}]

set_property IOSTANDARD LVDS_25 [get_ports channel_z_clk_p]
set_property DIFF_TERM TRUE [get_ports channel_z_clk_p]
set_property PACKAGE_PIN AC22 [get_ports channel_z_clk_n]
set_property IOSTANDARD LVDS_25 [get_ports channel_z_clk_n]
set_property DIFF_TERM TRUE [get_ports channel_z_clk_n]

set_property IOSTANDARD LVDS_25 [get_ports {channel_z_data_p[0]}]
set_property DIFF_TERM TRUE [get_ports {channel_z_data_p[0]}]
set_property PACKAGE_PIN AE21 [get_ports {channel_z_data_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_z_data_n[0]}]
set_property DIFF_TERM TRUE [get_ports {channel_z_data_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_z_data_p[1]}]
set_property DIFF_TERM TRUE [get_ports {channel_z_data_p[1]}]
set_property PACKAGE_PIN AF18 [get_ports {channel_z_data_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_z_data_n[1]}]
set_property DIFF_TERM TRUE [get_ports {channel_z_data_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_z_data_p[2]}]
set_property DIFF_TERM TRUE [get_ports {channel_z_data_p[2]}]
set_property PACKAGE_PIN AF20 [get_ports {channel_z_data_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_z_data_n[2]}]
set_property DIFF_TERM TRUE [get_ports {channel_z_data_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_z_data_p[3]}]
set_property DIFF_TERM TRUE [get_ports {channel_z_data_p[3]}]
set_property PACKAGE_PIN AF25 [get_ports {channel_z_data_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {channel_z_data_n[3]}]
set_property DIFF_TERM TRUE [get_ports {channel_z_data_n[3]}]

set_property IOSTANDARD LVDS [get_ports diff_clock_clk_p]
set_property DIFF_TERM TRUE [get_ports diff_clock_clk_p]
set_property PACKAGE_PIN L4 [get_ports diff_clock_clk_n]
set_property IOSTANDARD LVDS [get_ports diff_clock_clk_n]
set_property DIFF_TERM TRUE [get_ports diff_clock_clk_n]


set_property PACKAGE_PIN AE26 [get_ports rst_n]
set_property IOSTANDARD LVCMOS25 [get_ports rst_n]
#set_property IOSTANDARD LVCMOS18 [get_ports {data_out[27]}]

set_clock_groups -name cameralink -asynchronous -group [get_clocks {rx_mmcmout_x1 rx_mmcmout_xs channel_x_clk_p}]
set_clock_groups -name refclock -asynchronous -group [get_clocks diff_clock_clk_p]


#set_property IOSTANDARD LVCMOS18 [get_ports locked]
#set_property PACKAGE_PIN E6 [get_ports locked]

set_property IOSTANDARD LVDS [get_ports pixel_clk_out_p]
set_property DIFF_TERM TRUE [get_ports pixel_clk_out_p]
set_property PACKAGE_PIN F7 [get_ports pixel_clk_out_n]
set_property IOSTANDARD LVDS [get_ports pixel_clk_out_n]
set_property DIFF_TERM TRUE [get_ports pixel_clk_out_n]

set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_p[0]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_p[0]}]
set_property PACKAGE_PIN H8 [get_ports {vid_io_out_data_n[0]}]
set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_n[0]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_n[0]}]

set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_p[1]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_p[1]}]
set_property PACKAGE_PIN L7 [get_ports {vid_io_out_data_n[1]}]
set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_n[1]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_n[1]}]

set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_p[2]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_p[2]}]
set_property PACKAGE_PIN N6 [get_ports {vid_io_out_data_n[2]}]
set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_n[2]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_n[2]}]

set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_p[3]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_p[3]}]
set_property PACKAGE_PIN K7 [get_ports {vid_io_out_data_n[3]}]
set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_n[3]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_n[3]}]

set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_p[4]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_p[4]}]
set_property PACKAGE_PIN L8 [get_ports {vid_io_out_data_n[4]}]
set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_n[4]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_n[4]}]

set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_p[5]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_p[5]}]
set_property PACKAGE_PIN J6 [get_ports {vid_io_out_data_n[5]}]
set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_n[5]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_n[5]}]

set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_p[6]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_p[6]}]
set_property PACKAGE_PIN J5 [get_ports {vid_io_out_data_n[6]}]
set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_n[6]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_n[6]}]

set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_p[7]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_p[7]}]
set_property PACKAGE_PIN N2 [get_ports {vid_io_out_data_n[7]}]
set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_n[7]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_n[7]}]

set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_p[8]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_p[8]}]
set_property PACKAGE_PIN L2 [get_ports {vid_io_out_data_n[8]}]
set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_n[8]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_n[8]}]

set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_p[9]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_p[9]}]
set_property PACKAGE_PIN M1 [get_ports {vid_io_out_data_n[9]}]
set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_n[9]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_n[9]}]

set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_p[10]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_p[10]}]
set_property PACKAGE_PIN H3 [get_ports {vid_io_out_data_n[10]}]
set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_n[10]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_n[10]}]

set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_p[11]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_p[11]}]
set_property PACKAGE_PIN H1 [get_ports {vid_io_out_data_n[11]}]
set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_n[11]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_n[11]}]

set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_p[12]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_p[12]}]
set_property PACKAGE_PIN G1 [get_ports {vid_io_out_data_n[12]}]
set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_n[12]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_n[12]}]

set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_p[13]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_p[13]}]
set_property PACKAGE_PIN K1 [get_ports {vid_io_out_data_n[13]}]
set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_n[13]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_n[13]}]

set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_p[14]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_p[14]}]
set_property PACKAGE_PIN F4 [get_ports {vid_io_out_data_n[14]}]
set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_n[14]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_n[14]}]

set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_p[15]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_p[15]}]
set_property PACKAGE_PIN E3 [get_ports {vid_io_out_data_n[15]}]
set_property IOSTANDARD LVDS [get_ports {vid_io_out_data_n[15]}]
set_property DIFF_TERM TRUE [get_ports {vid_io_out_data_n[15]}]


set_property IOSTANDARD LVDS [get_ports vid_io_out_vsync_p]
set_property DIFF_TERM TRUE [get_ports vid_io_out_vsync_p]
set_property PACKAGE_PIN E1 [get_ports vid_io_out_vsync_n]
set_property IOSTANDARD LVDS [get_ports vid_io_out_vsync_n]
set_property DIFF_TERM TRUE [get_ports vid_io_out_vsync_n]


set_property IOSTANDARD LVDS [get_ports vid_io_out_hsync_p]
set_property DIFF_TERM TRUE [get_ports vid_io_out_hsync_p]
set_property PACKAGE_PIN C1 [get_ports vid_io_out_hsync_n]
set_property IOSTANDARD LVDS [get_ports vid_io_out_hsync_n]
set_property DIFF_TERM TRUE [get_ports vid_io_out_hsync_n]

set_property IOSTANDARD LVDS [get_ports vid_io_out_active_video_p]
set_property DIFF_TERM TRUE [get_ports vid_io_out_active_video_p]
set_property PACKAGE_PIN F2 [get_ports vid_io_out_active_video_n]
set_property IOSTANDARD LVDS [get_ports vid_io_out_active_video_n]
set_property DIFF_TERM TRUE [get_ports vid_io_out_active_video_n]

set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_0/m_axis_tdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_0/m_axis_tdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_0/m_axis_tdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_0/m_axis_tdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_0/m_axis_tdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_0/m_axis_tdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_0/m_axis_tdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_0/m_axis_tdata[3]}]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_0/m_axis_tvalid]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_dwidth_converter_0/m_axis_tuser[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/data_in[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/data_out[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/data_in[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/data_in[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/data_out[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/data_in[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/data_out[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/data_out[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/data_in[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/data_in[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/data_in[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/data_out[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/data_out[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/data_in[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/data_out[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/data_out[7]}]
set_property MARK_DEBUG true [get_nets {vid_io_out_data[3]}]
set_property MARK_DEBUG true [get_nets {vid_io_out_data[8]}]
set_property MARK_DEBUG true [get_nets {vid_io_out_data[0]}]
set_property MARK_DEBUG true [get_nets {vid_io_out_data[14]}]
set_property MARK_DEBUG true [get_nets {vid_io_out_data[12]}]
set_property MARK_DEBUG true [get_nets {vid_io_out_data[9]}]
set_property MARK_DEBUG true [get_nets {vid_io_out_data[4]}]
set_property MARK_DEBUG true [get_nets {vid_io_out_data[15]}]
set_property MARK_DEBUG true [get_nets {vid_io_out_data[10]}]
set_property MARK_DEBUG true [get_nets {vid_io_out_data[7]}]
set_property MARK_DEBUG true [get_nets {vid_io_out_data[6]}]
set_property MARK_DEBUG true [get_nets {vid_io_out_data[2]}]
set_property MARK_DEBUG true [get_nets {vid_io_out_data[13]}]
set_property MARK_DEBUG true [get_nets {vid_io_out_data[5]}]
set_property MARK_DEBUG true [get_nets {vid_io_out_data[1]}]
set_property MARK_DEBUG true [get_nets {vid_io_out_data[11]}]
set_property MARK_DEBUG true [get_nets vid_io_out_hsync]
set_property MARK_DEBUG true [get_nets vid_io_out_active_video]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/line_counter_homography[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/line_counter_homography[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/line_counter_homography[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/line_counter_homography[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/line_counter_homography[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/line_counter_homography[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/line_counter_homography[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/line_counter_homography[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/line_counter_homography[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/line_counter_homography[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/data_to_dmd[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/data_to_dmd[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/data_to_dmd[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/data_to_dmd[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/data_to_dmd[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/data_to_dmd[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/data_to_dmd[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/data_to_dmd[1]}]

set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/addr_image_in_b[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/addr_image_in_b[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/addr_image_in_b[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/addr_image_in_b[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/addr_image_in_b[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/addr_image_in_b[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/addr_image_in_b[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/addr_image_in_b[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/addr_image_in_b[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/addr_image_in_b[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/addr_image_in_b[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/addr_image_in_b[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/addr_image_in_b[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/dout_image_in_b[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/dout_image_in_b[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/dout_image_in_b[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/dout_image_in_b[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/dout_image_in_b[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/dout_image_in_b[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/dout_image_in_b[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/dout_image_in_b[7]}]
set_property MARK_DEBUG true [get_nets design_1_i/homography_latest_0/scan_start]
set_property MARK_DEBUG true [get_nets design_1_i/homography_latest_0/tvalid]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/doLookUpInst/count_data[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/doLookUpInst/count_data[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/doLookUpInst/count_data[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/doLookUpInst/count_data[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/doLookUpInst/count_data[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/doLookUpInst/count_data[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/homography_latest_0/inst/doLookUpInst/count_data[6]}]
set_property MARK_DEBUG true [get_nets design_1_i/address_gen_param_0/sof_to_homography]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_counter[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_pos_counter[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_counter[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_pos_counter[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_counter[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_counter[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_counter[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_pos_counter[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_pos_counter[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_counter[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_counter[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_counter[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_counter[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_counter[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_pos_counter[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_pos_counter[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_pos_counter[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/line_pos_counter[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/frame_counter[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/frame_counter[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/frame_counter[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/frame_counter[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/frame_counter[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/frame_counter[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/frame_counter[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/frame_counter[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/frame_counter[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/frame_counter[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/frame_counter[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/frame_counter[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/frame_counter[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/frame_counter[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/frame_counter[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/inst/frame_counter[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/bram_addr_in[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/bram_addr_in[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/bram_addr_in[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/bram_addr_in[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/bram_addr_in[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/bram_addr_in[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/bram_addr_in[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/bram_addr_in[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/bram_addr_in[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/bram_addr_in[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/bram_addr_in[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/bram_addr_in[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/address_gen_param_0/bram_addr_in[3]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_0_clk_out1]]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/address_gen_param_0/inst/frame_counter[0]} {design_1_i/address_gen_param_0/inst/frame_counter[1]} {design_1_i/address_gen_param_0/inst/frame_counter[2]} {design_1_i/address_gen_param_0/inst/frame_counter[3]} {design_1_i/address_gen_param_0/inst/frame_counter[4]} {design_1_i/address_gen_param_0/inst/frame_counter[5]} {design_1_i/address_gen_param_0/inst/frame_counter[6]} {design_1_i/address_gen_param_0/inst/frame_counter[7]} {design_1_i/address_gen_param_0/inst/frame_counter[8]} {design_1_i/address_gen_param_0/inst/frame_counter[9]} {design_1_i/address_gen_param_0/inst/frame_counter[10]} {design_1_i/address_gen_param_0/inst/frame_counter[11]} {design_1_i/address_gen_param_0/inst/frame_counter[12]} {design_1_i/address_gen_param_0/inst/frame_counter[13]} {design_1_i/address_gen_param_0/inst/frame_counter[14]} {design_1_i/address_gen_param_0/inst/frame_counter[15]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list design_1_i/clk_wiz_0_clk_out2]]
set_property port_width 7 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {design_1_i/homography_latest_0/inst/doLookUpInst/count_data[0]} {design_1_i/homography_latest_0/inst/doLookUpInst/count_data[1]} {design_1_i/homography_latest_0/inst/doLookUpInst/count_data[2]} {design_1_i/homography_latest_0/inst/doLookUpInst/count_data[3]} {design_1_i/homography_latest_0/inst/doLookUpInst/count_data[4]} {design_1_i/homography_latest_0/inst/doLookUpInst/count_data[5]} {design_1_i/homography_latest_0/inst/doLookUpInst/count_data[6]}]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list pixel_clk_out]]
set_property port_width 16 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {vid_io_out_data[0]} {vid_io_out_data[1]} {vid_io_out_data[2]} {vid_io_out_data[3]} {vid_io_out_data[4]} {vid_io_out_data[5]} {vid_io_out_data[6]} {vid_io_out_data[7]} {vid_io_out_data[8]} {vid_io_out_data[9]} {vid_io_out_data[10]} {vid_io_out_data[11]} {vid_io_out_data[12]} {vid_io_out_data[13]} {vid_io_out_data[14]} {vid_io_out_data[15]}]]
create_debug_port u_ila_0 probe
set_property port_width 10 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/address_gen_param_0/inst/line_counter[0]} {design_1_i/address_gen_param_0/inst/line_counter[1]} {design_1_i/address_gen_param_0/inst/line_counter[2]} {design_1_i/address_gen_param_0/inst/line_counter[3]} {design_1_i/address_gen_param_0/inst/line_counter[4]} {design_1_i/address_gen_param_0/inst/line_counter[5]} {design_1_i/address_gen_param_0/inst/line_counter[6]} {design_1_i/address_gen_param_0/inst/line_counter[7]} {design_1_i/address_gen_param_0/inst/line_counter[8]} {design_1_i/address_gen_param_0/inst/line_counter[9]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/address_gen_param_0/inst/line_pos_counter[0]} {design_1_i/address_gen_param_0/inst/line_pos_counter[1]} {design_1_i/address_gen_param_0/inst/line_pos_counter[2]} {design_1_i/address_gen_param_0/inst/line_pos_counter[3]} {design_1_i/address_gen_param_0/inst/line_pos_counter[4]} {design_1_i/address_gen_param_0/inst/line_pos_counter[5]} {design_1_i/address_gen_param_0/inst/line_pos_counter[6]} {design_1_i/address_gen_param_0/inst/line_pos_counter[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 64 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/axis_dwidth_converter_0/m_axis_tdata[0]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[1]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[2]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[3]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[4]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[5]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[6]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[7]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[8]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[9]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[10]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[11]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[12]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[13]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[14]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[15]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[16]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[17]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[18]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[19]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[20]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[21]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[22]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[23]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[24]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[25]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[26]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[27]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[28]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[29]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[30]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[31]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[32]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[33]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[34]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[35]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[36]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[37]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[38]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[39]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[40]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[41]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[42]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[43]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[44]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[45]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[46]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[47]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[48]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[49]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[50]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[51]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[52]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[53]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[54]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[55]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[56]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[57]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[58]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[59]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[60]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[61]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[62]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[63]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/axis_dwidth_converter_0/m_axis_tuser[0]} {design_1_i/axis_dwidth_converter_0/m_axis_tuser[1]} {design_1_i/axis_dwidth_converter_0/m_axis_tuser[2]} {design_1_i/axis_dwidth_converter_0/m_axis_tuser[3]} {design_1_i/axis_dwidth_converter_0/m_axis_tuser[4]} {design_1_i/axis_dwidth_converter_0/m_axis_tuser[5]} {design_1_i/axis_dwidth_converter_0/m_axis_tuser[6]} {design_1_i/axis_dwidth_converter_0/m_axis_tuser[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/address_gen_param_0/data_in[0]} {design_1_i/address_gen_param_0/data_in[1]} {design_1_i/address_gen_param_0/data_in[2]} {design_1_i/address_gen_param_0/data_in[3]} {design_1_i/address_gen_param_0/data_in[4]} {design_1_i/address_gen_param_0/data_in[5]} {design_1_i/address_gen_param_0/data_in[6]} {design_1_i/address_gen_param_0/data_in[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 13 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/address_gen_param_0/bram_addr_in[0]} {design_1_i/address_gen_param_0/bram_addr_in[1]} {design_1_i/address_gen_param_0/bram_addr_in[2]} {design_1_i/address_gen_param_0/bram_addr_in[3]} {design_1_i/address_gen_param_0/bram_addr_in[4]} {design_1_i/address_gen_param_0/bram_addr_in[5]} {design_1_i/address_gen_param_0/bram_addr_in[6]} {design_1_i/address_gen_param_0/bram_addr_in[7]} {design_1_i/address_gen_param_0/bram_addr_in[8]} {design_1_i/address_gen_param_0/bram_addr_in[9]} {design_1_i/address_gen_param_0/bram_addr_in[10]} {design_1_i/address_gen_param_0/bram_addr_in[11]} {design_1_i/address_gen_param_0/bram_addr_in[12]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/address_gen_param_0/data_out[0]} {design_1_i/address_gen_param_0/data_out[1]} {design_1_i/address_gen_param_0/data_out[2]} {design_1_i/address_gen_param_0/data_out[3]} {design_1_i/address_gen_param_0/data_out[4]} {design_1_i/address_gen_param_0/data_out[5]} {design_1_i/address_gen_param_0/data_out[6]} {design_1_i/address_gen_param_0/data_out[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/axis_dwidth_converter_0/m_axis_tvalid]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/address_gen_param_0/sof_to_homography]]
create_debug_port u_ila_1 probe
set_property port_width 8 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {design_1_i/homography_latest_0/dout_image_in_b[0]} {design_1_i/homography_latest_0/dout_image_in_b[1]} {design_1_i/homography_latest_0/dout_image_in_b[2]} {design_1_i/homography_latest_0/dout_image_in_b[3]} {design_1_i/homography_latest_0/dout_image_in_b[4]} {design_1_i/homography_latest_0/dout_image_in_b[5]} {design_1_i/homography_latest_0/dout_image_in_b[6]} {design_1_i/homography_latest_0/dout_image_in_b[7]}]]
create_debug_port u_ila_1 probe
set_property port_width 10 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list {design_1_i/homography_latest_0/inst/line_counter_homography[0]} {design_1_i/homography_latest_0/inst/line_counter_homography[1]} {design_1_i/homography_latest_0/inst/line_counter_homography[2]} {design_1_i/homography_latest_0/inst/line_counter_homography[3]} {design_1_i/homography_latest_0/inst/line_counter_homography[4]} {design_1_i/homography_latest_0/inst/line_counter_homography[5]} {design_1_i/homography_latest_0/inst/line_counter_homography[6]} {design_1_i/homography_latest_0/inst/line_counter_homography[7]} {design_1_i/homography_latest_0/inst/line_counter_homography[8]} {design_1_i/homography_latest_0/inst/line_counter_homography[9]}]]
create_debug_port u_ila_1 probe
set_property port_width 8 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list {design_1_i/homography_latest_0/data_to_dmd[0]} {design_1_i/homography_latest_0/data_to_dmd[1]} {design_1_i/homography_latest_0/data_to_dmd[2]} {design_1_i/homography_latest_0/data_to_dmd[3]} {design_1_i/homography_latest_0/data_to_dmd[4]} {design_1_i/homography_latest_0/data_to_dmd[5]} {design_1_i/homography_latest_0/data_to_dmd[6]} {design_1_i/homography_latest_0/data_to_dmd[7]}]]
create_debug_port u_ila_1 probe
set_property port_width 13 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list {design_1_i/homography_latest_0/addr_image_in_b[0]} {design_1_i/homography_latest_0/addr_image_in_b[1]} {design_1_i/homography_latest_0/addr_image_in_b[2]} {design_1_i/homography_latest_0/addr_image_in_b[3]} {design_1_i/homography_latest_0/addr_image_in_b[4]} {design_1_i/homography_latest_0/addr_image_in_b[5]} {design_1_i/homography_latest_0/addr_image_in_b[6]} {design_1_i/homography_latest_0/addr_image_in_b[7]} {design_1_i/homography_latest_0/addr_image_in_b[8]} {design_1_i/homography_latest_0/addr_image_in_b[9]} {design_1_i/homography_latest_0/addr_image_in_b[10]} {design_1_i/homography_latest_0/addr_image_in_b[11]} {design_1_i/homography_latest_0/addr_image_in_b[12]}]]
create_debug_port u_ila_1 probe
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list design_1_i/homography_latest_0_tvalid]]
create_debug_port u_ila_1 probe
set_property port_width 1 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list design_1_i/homography_latest_0/scan_start]]
create_debug_port u_ila_1 probe
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list design_1_i/homography_latest_0/tvalid]]
create_debug_port u_ila_2 probe
set_property port_width 1 [get_debug_ports u_ila_2/probe1]
connect_debug_port u_ila_2/probe1 [get_nets [list vid_io_out_active_video]]
create_debug_port u_ila_2 probe
set_property port_width 1 [get_debug_ports u_ila_2/probe2]
connect_debug_port u_ila_2/probe2 [get_nets [list vid_io_out_hsync]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_wiz_0_clk_out1]
