// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 


module hls_threshold (
        ap_clk,
        ap_rst_n,
        src_TDATA,
        src_TVALID,
        src_TREADY,
        src_TKEEP,
        src_TSTRB,
        src_TUSER,
        src_TLAST,
        src_TID,
        src_TDEST,
        ap_const_lv8_64,
        dst_TDATA,
        dst_TVALID,
        dst_TREADY,
        dst_TKEEP,
        dst_TSTRB,
        dst_TUSER,
        dst_TLAST,
        dst_TID,
        dst_TDEST
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 1'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
//parameter    ap_const_lv8_64 = 8'b11111010;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv32_27 = 32'b100111;
parameter    ap_const_lv32_28 = 32'b101000;
parameter    ap_const_lv32_2F = 32'b101111;
parameter    ap_const_lv32_30 = 32'b110000;
parameter    ap_const_lv32_37 = 32'b110111;
parameter    ap_const_lv32_38 = 32'b111000;
parameter    ap_const_lv32_3F = 32'b111111;
parameter    ap_true = 1'b1;

input [7:0] ap_const_lv8_64;
input   ap_clk;
input   ap_rst_n;
input  [63:0] src_TDATA;
input   src_TVALID;
output   src_TREADY;
input  [7:0] src_TKEEP;
input  [7:0] src_TSTRB;
input  [0:0] src_TUSER;
input  [0:0] src_TLAST;
input  [0:0] src_TID;
input  [0:0] src_TDEST;
output  [7:0] dst_TDATA;
output   dst_TVALID;
input   dst_TREADY;
output  [0:0] dst_TKEEP;
output  [0:0] dst_TSTRB;
output  [0:0] dst_TUSER;
output  [0:0] dst_TLAST;
output  [0:0] dst_TID;
output  [0:0] dst_TDEST;

reg src_TREADY;
reg dst_TVALID;
reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm = 1'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_42;
reg    ap_sig_ioackin_dst_TREADY;
reg    ap_reg_ioackin_dst_TREADY = 1'b0;
wire   [7:0] tmp_fu_158_p1;
wire   [7:0] tmp_pixel_1_fu_168_p4;
wire   [7:0] tmp_pixel_2_fu_184_p4;
wire   [7:0] tmp_pixel_3_fu_200_p4;
wire   [7:0] tmp_pixel_4_fu_216_p4;
wire   [7:0] tmp_pixel_5_fu_232_p4;
wire   [7:0] tmp_pixel_6_fu_248_p4;
wire   [7:0] tmp_pixel_7_fu_264_p4;
wire   [0:0] tmp_4_fu_162_p2;
wire   [0:0] tmp_4_1_fu_178_p2;
wire   [0:0] tmp_4_2_fu_194_p2;
wire   [0:0] tmp_4_3_fu_210_p2;
wire   [0:0] tmp_4_4_fu_226_p2;
wire   [0:0] tmp_4_5_fu_242_p2;
wire   [0:0] tmp_4_6_fu_258_p2;
wire   [0:0] tmp_4_7_fu_274_p2;
reg   [0:0] ap_NS_fsm;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ioackin_dst_TREADY assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_dst_TREADY
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_dst_TREADY <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~((src_TVALID == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_dst_TREADY)))) begin
            ap_reg_ioackin_dst_TREADY <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(src_TVALID == ap_const_logic_0) & (ap_const_logic_1 == dst_TREADY))) begin
            ap_reg_ioackin_dst_TREADY <= ap_const_logic_1;
        end
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_42)
begin
    if (ap_sig_bdd_42) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_ioackin_dst_TREADY assign process. ///
always @ (dst_TREADY or ap_reg_ioackin_dst_TREADY)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_dst_TREADY)) begin
        ap_sig_ioackin_dst_TREADY = dst_TREADY;
    end else begin
        ap_sig_ioackin_dst_TREADY = ap_const_logic_1;
    end
end

/// dst_TVALID assign process. ///
always @ (src_TVALID or ap_sig_cseq_ST_st1_fsm_0 or ap_reg_ioackin_dst_TREADY)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(src_TVALID == ap_const_logic_0) & (ap_const_logic_0 == ap_reg_ioackin_dst_TREADY))) begin
        dst_TVALID = ap_const_logic_1;
    end else begin
        dst_TVALID = ap_const_logic_0;
    end
end

/// src_TREADY assign process. ///
always @ (src_TVALID or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_ioackin_dst_TREADY)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~((src_TVALID == ap_const_logic_0) | (ap_const_logic_0 == ap_sig_ioackin_dst_TREADY)))) begin
        src_TREADY = ap_const_logic_1;
    end else begin
        src_TREADY = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (src_TVALID or ap_CS_fsm or ap_sig_ioackin_dst_TREADY)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


/// ap_rst_n_inv assign process. ///
always @ (ap_rst_n)
begin
    ap_rst_n_inv = ~ap_rst_n;
end

/// ap_sig_bdd_42 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_42 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end
assign dst_TDATA = {{{{{{{{{{{{{{tmp_4_fu_162_p2}, {tmp_4_1_fu_178_p2}}}, {tmp_4_2_fu_194_p2}}}, {tmp_4_3_fu_210_p2}}}, {tmp_4_4_fu_226_p2}}}, {tmp_4_5_fu_242_p2}}}, {tmp_4_6_fu_258_p2}}}, {tmp_4_7_fu_274_p2}};
assign dst_TDEST = src_TID;
assign dst_TID = src_TID;
assign dst_TKEEP = src_TKEEP[0:0];
assign dst_TLAST = src_TLAST;
assign dst_TSTRB = src_TSTRB[0:0];
assign dst_TUSER = src_TUSER;
assign tmp_4_1_fu_178_p2 = (tmp_pixel_1_fu_168_p4 >= ap_const_lv8_64? 1'b0: 1'b1);
assign tmp_4_2_fu_194_p2 = (tmp_pixel_2_fu_184_p4 >= ap_const_lv8_64? 1'b0: 1'b1);
assign tmp_4_3_fu_210_p2 = (tmp_pixel_3_fu_200_p4 >= ap_const_lv8_64? 1'b0: 1'b1);
assign tmp_4_4_fu_226_p2 = (tmp_pixel_4_fu_216_p4 >= ap_const_lv8_64? 1'b0: 1'b1);
assign tmp_4_5_fu_242_p2 = (tmp_pixel_5_fu_232_p4 >= ap_const_lv8_64? 1'b0: 1'b1);
assign tmp_4_6_fu_258_p2 = (tmp_pixel_6_fu_248_p4 >= ap_const_lv8_64? 1'b0: 1'b1);
assign tmp_4_7_fu_274_p2 = (tmp_pixel_7_fu_264_p4 >= ap_const_lv8_64? 1'b0: 1'b1);
assign tmp_4_fu_162_p2 = (tmp_fu_158_p1 > ap_const_lv8_64? 1'b0: 1'b1);
assign tmp_fu_158_p1 = src_TDATA[7:0];
assign tmp_pixel_1_fu_168_p4 = {{src_TDATA[ap_const_lv32_F : ap_const_lv32_8]}};
assign tmp_pixel_2_fu_184_p4 = {{src_TDATA[ap_const_lv32_17 : ap_const_lv32_10]}};
assign tmp_pixel_3_fu_200_p4 = {{src_TDATA[ap_const_lv32_1F : ap_const_lv32_18]}};
assign tmp_pixel_4_fu_216_p4 = {{src_TDATA[ap_const_lv32_27 : ap_const_lv32_20]}};
assign tmp_pixel_5_fu_232_p4 = {{src_TDATA[ap_const_lv32_2F : ap_const_lv32_28]}};
assign tmp_pixel_6_fu_248_p4 = {{src_TDATA[ap_const_lv32_37 : ap_const_lv32_30]}};
assign tmp_pixel_7_fu_264_p4 = {{src_TDATA[ap_const_lv32_3F : ap_const_lv32_38]}};


endmodule //hls_threshold

