# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z030fbg676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ilim/arm_core_load_single_with_bike/a(2).tmp/address_gen_param_v1_0_project/address_gen_param_v1_0_project.cache/wt [current_project]
set_property parent.project_path /home/ilim/arm_core_load_single_with_bike/a(2).tmp/address_gen_param_v1_0_project/address_gen_param_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/ilim/arm_core_load_single_with_bike/repo [current_project]
read_verilog -library xil_defaultlib /home/ilim/arm_core_load_single_with_bike/repo/Addr_gen_blackout/sources_1/new/adress_gen.v
synth_design -top address_gen_param -part xc7z030fbg676-1
write_checkpoint -noxdef address_gen_param.dcp
catch { report_utilization -file address_gen_param_utilization_synth.rpt -pb address_gen_param_utilization_synth.pb }
