webtalk_init -webtalk_dir /home/ilim/arm_core_load_single_with_bike/a.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jul  7 15:49:19 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1266856" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174679548_176449548_210570730_342" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c5d054c7b43e577586ade2db04e767d4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c65a652e-4756-4c70-b07a-67bedc080973" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "36" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "789.750 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2609.625 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key cable -value "Digilent/JTAG-HS3/15000000" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "000040001372C093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Digilent/JTAG-HS3/15000000" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "000040001372C093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_transmit -clientid 1801283332 -regid "174679548_176449548_210570730_342" -xml /home/ilim/arm_core_load_single_with_bike/a.hw/webtalk/usage_statistics_ext_labtool.xml -html /home/ilim/arm_core_load_single_with_bike/a.hw/webtalk/usage_statistics_ext_labtool.html -wdm /home/ilim/arm_core_load_single_with_bike/a.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
